guard 'coffeescript', :output => 'public/javascripts/compiled' do
  watch(%r{^app/coffeescripts/(.*)\.coffee})
end

guard 'coffeescript', :output => 'spec/javascripts' do
  watch(%r{^spec/coffeescripts/(.*)\.coffee})
end
