guard 'coffeescript', :output => 'public/javascripts/compiled', :bare => true do
  watch(%r{^app/coffeescripts/(.*)\.coffee})
end

guard 'coffeescript', :output => 'spec/javascripts', :bare => true do
  watch(%r{^spec/coffeescripts/(.*)\.coffee})
end
